[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/:resource"
  to = "/data/:resource.json"
  status = 200
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/:resource/messages"
  to = "/data/:resource/messages.json"
  status = 200
  headers = {X-From = "Netlify"}
